# As there are no releases in GN, we build the latest tag from time to time.
# The version is the time of the latest master commit in YYYYMMDDHHMMSS
# notation.

{% set name = "gn" %}
{% set version = "0.0.20250416202228" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # We have to use git as the source as the provided tarballs are not stable.
  git_url: https://gn.googlesource.com/gn
  git_rev: 10a27145cd0770b78745ff536e343bf12c70f6c3
  # patches:
  #   - add-lrt.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - ninja
  host:
  run:

test:
  commands:
    - test -f $PREFIX/bin/gn  # [unix]
    - if not exist %PREFIX%\\bin\\gn.exe exit 1  # [win]

about:
  home: https://gn.googlesource.com/gn/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'GN is a meta-build system that generates build files for Ninja.'

extra:
  recipe-maintainers:
    - xhochy
